services:
  vane:
    image: itzcrazykns1337/vane:latest
    build:
      context: .
    environment:
      - HOST=0.0.0.0
    network_mode: host
    volumes:
      - data:/home/vane/data
    restart: unless-stopped

volumes:
  data:
    name: 'vane-data'
