engines:
- disabled: false
  engine: google
  name: google
- disabled: false
  engine: bing
  name: bing
- disabled: true
  engine: startpage
  name: startpage
- disabled: false
  engine: wikipedia
  name: wikipedia
- disabled: false
  engine: wikidata
  name: wikidata
- disabled: false
  engine: arxiv
  name: arxiv
- disabled: false
  engine: github
  name: github
- disabled: false
  engine: reddit
  name: reddit
- disabled: false
  engine: wolframalpha
  name: wolframalpha
- api_key: BSAXBBOjWZ-EJ0bqWNOgFjNnOanEl_5
  disabled: false
  engine: braveapi
  max_connections: 1
  name: braveapi
  rate_limit: 1.1
- disabled: false
  engine: google-news
  name: google-news
general:
  instance_name: searxng
outgoing:
  max_connections: 100
  max_request_timeout: 20.0
  pool_max_size: 20
  request_timeout: 10.0
search:
  autocomplete: google
  formats:
  - html
  - json
server:
  limiter: false
  secret_key: a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b
ui:
  static_use_hash: true
use_default_settings: true
